### ISSUE TITLE
Sorbet support?

### ISSUE THREAD

**Issue by devonpmack** [Shopify/fixture_factory#19]
Is it possible to get strong typing on the `create` and `build` methods?

Right now we are unfortunately losing a lot of the advantages of Sorbet by using fixture factory, since the create methods returns untyped objects. I'm not sure if it's possible to add typing support but it would be very helpful.

**Comment by andyw8** [comment]
cc @Shopify/sorbet

This is quite often used in Core (483 hits for `define_factories`).

**Comment by egiurleo** [comment]
I added this to the discussion topics for our typing stream meeting on Monday.

**Comment by Morriar** [comment]
@devonpmack, sadly, I don't think we'll be able to do much considering the API of `fixture_factory`.

For `create` and `build`, it seems the return type would need to be inferred from the symbol passed as first parameter. This means those methods can return basically anything and the best option we have here is to return `T.untyped` as to allow any call on the returned value.

One solution we can recommend _if_ you want to benefit from typing with `ficxture_factory` is to cast the return value to the type you expect:

```rb
account = build(:account, plan: :enterprise)
account = T.cast(account, Account)
```

**Comment by andyw8** [comment]
I'll close since this Devon is no longer at Shopify.
